### ISSUE TITLE
License: why is it GPL, while the majority of ethereumjs is MPL?

### ISSUE THREAD

**Issue by axic** [ethereum/ethereumjs-account#1]
Would it be possible switching to MPL or MIT?

**Comment by wanderer** [comment]
Changed to MPL-2.0

**Comment by axic** [comment]
Don't want to be nitpicking, but you've changed `package.json` to `MLP-2.0` and not `MPL-2.0` :)

**Comment by wanderer** [comment]
omg! i probably just did that for all the packages :I
